### ISSUE TITLE
Feature Request: option to disable seconds (only hours and minutes)

### ISSUE THREAD

**Issue by erlangparasu** [DeweyReed/ScrollHmsPicker#2]

**Comment by DeweyReed** [comment]
It sounds good to me. I'll add it when I have time.

**Comment by DeweyReed** [comment]
With 2.0.1, call `hmsScrollPicker.setSecondsVisiblity(false)` or `app:shp_show_seconds="false"` to hide seconds.

**Comment by erlangparasu** [comment]
Thank you :D :+1:
