### ISSUE TITLE
Feature request - is there are possibility to change text size ?

### ISSUE THREAD

**Issue by tised** [DeweyReed/ScrollHmsPicker#5]
Hello! Thanks for the lib, I wonder if there is any chance to change the font size of the dialog items? Such as hours/minutes

I do see only typeface change possibility

Thanks!

**Comment by DeweyReed** [comment]
I check the code quickly, and I find two ways.

1. Override resources.

    Define these resources in your `dimens.xml` and change the value to what you want:

    ```XML
    <dimen name="shp_text_size_normal_item">36dp</dimen>
    <dimen name="shp_text_size_selected_item">52dp</dimen>
    <dimen name="shp_text_size_label">20dp</dimen>
    ```

1. Fork the repo, import the `library` module into your project, and do whatever you want.

**Comment by tised** [comment]
Thanks!
